Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: handler.LambdaHandler::handleRequest
      CodeUri: /Users/renato.dev/Desktop/HD Dev2/Estudo/senac-qa-test/curso-automacao-aluno/lambda-test/lambda-function
      Runtime: java8.al2
      Architectures:
        - x86_64